### ISSUE TITLE
CMake Error at cudpp_generated_sa_app.cu.o.cmake

### ISSUE THREAD

**Issue by simone164** [cudpp/cudpp#157]
Hi, I'm using cuda 4.2, cuda sdk 4.2 and cudpp 2.2, I have this problem when I try to build, cmake nothing errors but make return this:

/usr/local/cudpp-master/ext/cub/cub/device/dispatch/../../agent/agent_spmv.cuh(112): error: TexRefInputIterator is not a template

/usr/local/cudpp-master/ext/cub/cub/iterator/tex_obj_input_iterator.cuh(148): error: identifier "cudaTextureObject_t" is undefined

/usr/local/cudpp-master/ext/cub/cub/device/dispatch/dispatch_radix_sort.cuh(877): error: identifier "cudaErrorNotSupported" is undefined
          detected during:
            instantiation of "cudaError_t cub::DispatchRadixSort<DESCENDING, ALT_STORAGE, Key, Value, OffsetT>::Dispatch(void *, size_t &, cub::DoubleBuffer<Key> &, cub::DoubleBuffer<Value> &, OffsetT, int, int, cudaStream_t, __nv_bool) [with DESCENDING=false, ALT_STORAGE=false, Key=unsigned int, Value=unsigned int, OffsetT=int]" 
/usr/local/cudpp-master/ext/cub/cub/device/device_radix_sort.cuh(271): here
            instantiation of "cudaError_t cub::DeviceRadixSort::SortPairs(void *, size_t &, cub::DoubleBuffer<Key> &, cub::DoubleBuffer<Value> &, int, int, int, cudaStream_t, __nv_bool) [with Key=unsigned int, Value=unsigned int]" 
/usr/local/cudpp-master/src/cudpp/app/sa_app.cu(81): here

3 errors detected in the compilation of "/tmp/tmpxft_00000e07_00000000-4_sa_app.cpp1.ii".
CMake Error at cudpp_generated_sa_app.cu.o.cmake:264 (message):
  Error generating file
  /usr/local/cudpp-master/src/cudpp/CMakeFiles/cudpp.dir/app/./cudpp_generated_sa_app.cu.o

make[2]: *** [src/cudpp/CMakeFiles/cudpp.dir/app/./cudpp_generated_sa_app.cu.o] Error 1
make[1]: *** [src/cudpp/CMakeFiles/cudpp.dir/all] Error 2
make: *** [all] Error 2

**Comment by harrism** [comment]
My opinion is that CUDA 4.2 is too old for the CUDPP team to support. Can you upgrade to a newer release of the CUDA Toolkit? It's up to 7.0, and the 7.5 RC is about to appear, so 4.2 is very old.

**Comment by simone164** [comment]
Yes, with cuda 7.0 cudpp is perfect, it compile without problem. But I need of cuda SDK 4.2 to compile Medusa (https://github.com/JianlongZhong/Medusa). Thanks for the response, I will try an alternative

**Comment by yzhwang** [comment]
@simone164 If you want to do graph analytics on the GPU, I recommend an alternative CUDA library: Gunrock: http://gunrock.github.io/gunrock/ It shows better performance and is also under active development.
