### ISSUE TITLE
Fix SA limits in documentation

### ISSUE THREAD

**Issue by Bulat-Ziganshin** [cudpp/cudpp#162]
Documentation says "The SA is GPU memory bounded, it needs about seven times size of input data." that look pretty typical limit

But readme.md and http://cudpp.github.io/cudpp/2.2/index.html says about 10x lower limit:

CUDPP_SA	0.015 GPU memo

it probably should be "0.14" or so?

**Comment by Laurawly** [comment]
Thanks @Bulat-Ziganshin ! Fixed.
